services:
  ad-meet-calendar:
    build:
      context: .
    container_name: ad-meet-calendar-service
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html  
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ad-meet-calendar-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: calendarDB
    ports:
      - "6666:27017"

  postgresql:
    image: postgres:15
    container_name: ad-meet-calendar-postgresql
    restart: always
    environment:
      POSTGRES_USER: lutherdev
      POSTGRES_PASSWORD: calDBstr0ng
      POSTGRES_DB: calendarDB
    ports:
      - "3333:5432"

volumes:
  ad-meet-calendar-mongodb:
    driver: local
  ad-meet-calendar-postgresql:
    driver: local
